{{- $pool := .Values.rosa.machinePools.platform }}
{{- if and $pool.enabled $pool.clusterID }}
---
apiVersion: machine.openshift.io/v1beta1
kind: MachinePool
metadata:
  name: {{ $pool.name }}
  namespace: openshift-machine-api
spec:
  clusterID: {{ $pool.clusterID | quote }}
  name: {{ $pool.name }}
  replicas: {{ $pool.replicas }}
  {{- with $pool.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pool.taints }}
  taints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
